### ISSUE TITLE
"404 not found" when attempting to download

### ISSUE THREAD

**Issue by algvr** [yixchen/HOT#1]
Dear authors,

thank you for your amazing work! Unfortunately, I receive a 404 error when navigating to https://hot.is.tue.mpg.de/download.php to download the data, even after registering and signing in.

Could you please help?
Thanks in advance!

Edit: I think the issue is that the link should be https://hot.is.tue.mpg.de/download.html, not https://hot.is.tue.mpg.de/download.php.

**Comment by yixchen** [comment]
Yes, that's correct. I have corrected the links on the website. Thanks!
