### ISSUE TITLE
Question about the HOT-Annotated

### ISSUE THREAD

**Issue by hnuzhy** [yixchen/HOT#2]
Hello, thank you for your excellent and meaningful work and HOT dataset. I have download the released HOT v1.0 dataset. But I found that the total images in HOT-Annotated are `12,678`, which is not consistent with the number written in the paper `15,082`.  Is it normal? Or will the absent images be released in a later version? Hope to receive your reply!

**Comment by yixchen** [comment]
Hi, thanks for letting us know. It seems part of the 'HAKE' data was left out in the current version, and we will update the data files on the server in a couple of days. Thanks again.

**Comment by hnuzhy** [comment]
OK. Thank you for your relpy.

**Comment by catalyster** [comment]
Hello, thank you for your excellent work. I downloaded the HOT-Annotated yesterday and found that the number of the dataset is still 12678. When do you plan to modify the dataset to match the description in the paper？ Looking forward to your reply！

**Comment by yixchen** [comment]
Hi, the HOT-Annotated set has been updated on the download page. Please check it out!
